version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./model.joblib:/app/model.joblib
      - ./scaler.joblib:/app/scaler.joblib
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
